import { useState } from "react";
import { RefreshCw, Send, Server, Shield, Wifi } from "lucide-react";
import { StatusCard } from "../components/dashboard/StatusCard";
import { MonitorStatus } from "../components/dashboard/MonitorStatus";
import { SecurityEventTable } from "../components/dashboard/SecurityEventTable";
import { EventModal } from "../components/events/EventModal";
import { ErrorState } from "../components/common/ErrorState";
import { Loading } from "../components/common/Loading";
import { useEvents } from "../hooks/useEvents";
import { useSystemStatus } from "../hooks/useSystemStatus";
import { useTelegramTest } from "../hooks/useTelegramTest";

export function Dashboard() { const [selected, setSelected] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const status = useSystemStatus(); const events = useEvents(); const telegram = useTelegramTest(); const refresh = () => { void status.refetch(); void events.refetch(); }; const sendTest = () => telegram.mutate(undefined, { onSuccess: () => setNotice("Telegram alert sent successfully"), onError: () => setNotice("Failed to send Telegram alert") }); if (status.isLoading) return <Loading label="Loading monitoring dashboard..."/>; if (status.isError || !status.data) return <ErrorState onRetry={refresh}/>; const data = status.data; return <><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold tracking-wider text-cyan-400">OVERVIEW</p><h2 className="mt-1 text-2xl font-semibold">Security dashboard</h2><p className="mt-1 text-sm text-slate-400">Live monitoring of ASA configuration changes.</p></div><div className="flex gap-2"><button onClick={refresh} className="inline-flex items-center gap-2 rounded-md border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800"><RefreshCw size={16}/>Refresh</button><button disabled={telegram.isPending} onClick={sendTest} className="inline-flex items-center gap-2 rounded-md bg-cyan-500 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50"><Send size={16}/>{telegram.isPending ? "Sending..." : "Test Telegram"}</button></div></div>{notice && <div className="mb-5 rounded-md border border-cyan-800 bg-cyan-950/40 px-4 py-3 text-sm text-cyan-200">{notice}<button className="float-right" onClick={() => setNotice(null)}>×</button></div>}<section className="grid gap-4 md:grid-cols-3"><StatusCard title="ASA FIREWALL" status={data.asa_ip} subtitle="Online" icon={<Shield size={19} className="text-emerald-400"/>}/><StatusCard title="GRAYLOG" status={data.graylog.toUpperCase()} subtitle={data.graylog_url} icon={<Server size={19} className={data.graylog === "connected" ? "text-emerald-400" : "text-amber-400"}/>}/><StatusCard title="TELEGRAM" status={data.telegram.toUpperCase()} subtitle="Bot alert service" icon={<Wifi size={19} className="text-cyan-400"/>}/></section><div className="my-4"><MonitorStatus status={data}/></div><section><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold tracking-wider text-cyan-400">ACTIVITY</p><h2 className="mt-1 text-xl font-semibold">Recent Security Events</h2></div><span className="text-sm text-slate-400">{events.data?.length ?? 0} events</span></div>{events.isLoading ? <Loading label="Loading security events..."/> : events.isError ? <ErrorState onRetry={() => void events.refetch()}/> : <SecurityEventTable events={events.data ?? []} onView={setSelected}/>}</section><EventModal eventId={selected} onClose={() => setSelected(null)}/></>; }
