import { useMemo, useState } from "react";
import { RefreshCw, Search } from "lucide-react";
import { SecurityEventTable } from "../components/dashboard/SecurityEventTable";
import { EventModal } from "../components/events/EventModal";
import { ErrorState } from "../components/common/ErrorState";
import { Loading } from "../components/common/Loading";
import { useEvents } from "../hooks/useEvents";
import type { Severity } from "../types/event";
export function Events() { const [query, setQuery] = useState(""); const [severity, setSeverity] = useState<"ALL" | Severity>("ALL"); const [selected, setSelected] = useState<string | null>(null); const events = useEvents(); const filtered = useMemo(() => (events.data ?? []).filter(event => { const match = `${event.message} ${event.event_type} ${event.source_ip}`.toLowerCase().includes(query.toLowerCase()); return match && (severity === "ALL" || event.severity === severity); }), [events.data, query, severity]); return <><div className="mb-7"><p className="text-xs font-semibold tracking-wider text-cyan-400">EVENT LOG</p><h2 className="mt-1 text-2xl font-semibold">Events</h2><p className="mt-1 text-sm text-slate-400">Search and review detected ASA security events.</p></div><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-md border border-slate-700 bg-slate-900 px-3 text-slate-400"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search events..." className="w-full bg-transparent py-2.5 text-sm text-white outline-none"/></label><select value={severity} onChange={event => setSeverity(event.target.value as "ALL" | Severity)} className="rounded-md border border-slate-700 bg-slate-900 px-3 text-sm text-slate-200"><option value="ALL">All severities</option><option value="INFO">Info</option><option value="WARNING">Warning</option><option value="CRITICAL">Critical</option></select><button onClick={() => void events.refetch()} className="inline-flex items-center justify-center gap-2 rounded-md border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800"><RefreshCw size={16}/>Refresh</button></div><p className="mb-3 text-sm text-slate-400">{filtered.length} events</p>{events.isLoading ? <Loading label="Loading security events..."/> : events.isError ? <ErrorState onRetry={() => void events.refetch()}/> : <SecurityEventTable events={filtered} onView={setSelected}/>}<EventModal eventId={selected} onClose={() => setSelected(null)}/></>; }
